#!/bin/bash

#xrandr --dpi 144
xrdb -merge ~/.Xresources

# input
ibus-daemon &

nitrogen --restore

# notifications daemon
dunst &

# Pulseaudio tray icon/chooser
pasystray &

# Make caps another ctrl
setxkbmap -layout us -option ctrl:nocaps

# Make right alt/win compose
setxkbmap -option compose:rwin

# disable touchpad if it exists
synaptics_id=$(xinput --list | awk -v search="SynPS/2" \
    '$0 ~ search {match($0, /id=[0-9]+/); \
                  if (RSTART) \
                    print substr($0, RSTART+3, RLENGTH-3) \
                 }' | head -n1 \
     )
if [[ ! -z "${synaptics_id}" ]];
then
  xinput disable ${synaptics_id}
fi

# Increase keyboard repeat
xset r rate 220 43

# Turn off the monitor after ten minutes idle
xset dpms 0 0 600

# Then disable it since we let i3lock turn this on
xset -dpms

# Compositor
compton -f -b -D 2

## Start nm-applet for systray
nm-applet &

## Start Thunar Daemon
thunar --daemon &

## Start xscreensaver
# xscreensaver -no-splash &

# turn off the leds on a razer mouse
type razercfg >/dev/null 2>&1 && razercfg -l all:off

## Start Clipboard manager
(sleep 3s && clipit) &

emojione-picker &

# redshift color temperature
redshift-gtk &

slack &
