#!/bin/bash

#########################################3
# X settings
#########################################3

# load Xresources
xrdb -merge ~/.Xresources

#########################################3
# Helper daemons
#########################################3

# input
ibus-daemon &

# restore wallpaper
(sleep 5s && nitrogen --restore) &

# file manager daemon
thunar --daemon &

# polkit
/usr/lib/polkit-gnome-authentication-agent-1 &

#########################################3
# Tray Apps
#########################################3

# Pulseaudio tray icon/chooser
pasystray &

## Start nm-applet for systray
nm-applet &

## Start Clipboard manager
clipit &

emojione-picker &

#########################################3
# Desktop Apps
#########################################3

slack &

#########################################3
# Misc
#########################################3

#~/.local/bin/xss-lock i3lock &
