#!/bin/bash

#########################################3
# X settings
#########################################3

# adjust dpi
xrandr --dpi 144

# Make right alt/win compose
setxkbmap -option compose:rwin

xset dpms 3000 3000 3000

#########################################3
# Misc
#########################################3

# turn off the leds on a razer mouse
type razercfg >/dev/null 2>&1 && razercfg -l all:off

# load randr
~/.screenlayout/trihead.sh

# notifications daemon
dunst &
