#!/bin/bash

####################################
# X Settings
####################################

#xrandr --dpi 144
xrdb -merge ~/.Xresources

# Make caps another ctrl
setxkbmap -layout us -option ctrl:nocaps

# Make right alt/win compose
setxkbmap -option compose:rwin

# disable touchpad if it exists
synaptics_id=$(xinput --list | awk -v search="SynPS/2" \
    '$0 ~ search {match($0, /id=[0-9]+/); \
                  if (RSTART) \
                    print substr($0, RSTART+3, RLENGTH-3) \
                 }' | head -n1 \
     )
if [[ ! -z "${synaptics_id}" ]];
then
  xinput disable ${synaptics_id}
fi

# Increase keyboard repeat
xset r rate 220 43

# Turn off the monitor after ten minutes idle
xset dpms 0 0 600

# Then disable it since we let i3lock turn this on
xset -dpms

####################################
# Helpers
####################################

# polkit auth agent
/usr/lib/polkit-gnome-authentication-agent-1 &

# input selector agent
ibus-daemon &

# Compositor
compton -f -b -D 2

# restore wallpaper
nitrogen --restore

## Start Thunar Daemon
thunar --daemon &

####################################
# Tray Applications
####################################

## Start nm-applet for systray
nm-applet &

## Start Clipboard manager
(sleep 3s && clipit) &

emojione-picker &

# redshift color temperature
redshift-gtk &

# notifications daemon
dunst &

# Pulseaudio tray icon/chooser
pasystray &
