#!/bin/bash

#########################################3
# X settings
#########################################3

# load Xresources
xrdb -merge ~/.Xresources

# Make caps another ctrl
setxkbmap -layout us -option ctrl:nocaps

# Make right alt/win compose
setxkbmap -option compose:rwin

# Increase keyboard repeat
xset r rate 220 43

# Turn off the monitor after 11 minutes idle
xset dpms 660 660 660

#########################################3
# Helper daemons
#########################################3

# input
ibus-daemon &

# restore wallpaper
nitrogen --restore

# file manager daemon
thunar --daemon &

# Compositor
compton -f -b -D 2

# polkit
/usr/lib/polkit-gnome-authentication-agent-1 &

#########################################3
# Tray Apps
#########################################3

# notifications daemon
dunst &

# Pulseaudio tray icon/chooser
pasystray &

## Start nm-applet for systray
nm-applet &

## Start Clipboard manager
(sleep 3s && clipit) &

emojione-picker &

# redshift color temperature
redshift-gtk &

#########################################3
# Desktop Apps
#########################################3

slack &

#########################################3
# Misc
#########################################3

~/.local/bin/xss-lock i3lock &
