#!/bin/bash

# Make PrtSc Compose (it's in the right super position on my Thinkpad)
setxkbmap -option compose:prsc

# disable touchpad if it exists
synaptics_id=$(xinput --list | awk -v search="SynPS/2" \
    '$0 ~ search {match($0, /id=[0-9]+/); \
                  if (RSTART) \
                    print substr($0, RSTART+3, RLENGTH-3) \
                 }' | head -n1 \
     )
if [[ ! -z "${synaptics_id}" ]];
then
  xinput disable ${synaptics_id}
fi

# screen lock on lid close
~/.local/bin/xss-lock "flock -n /tmp/r2lockscreen -c dm-tool lock" &
