#!/usr/bin/env bash

pkill -f polybar

display_count=$(xrandr | grep -c ' connected')
lconf=~/.config/polybar/laptop
dconf=~/.config/polybar/desktop

if [[ "${display_count}" -eq 1 ]];
then
  MONITOR=eDP-1 polybar -c ${lconf} main &
else
  MONITOR=DP-0 polybar -c ${dconf} main &
  MONITOR=DP-2 polybar -c ${dconf} left &
  MONITOR=DP-4 polybar -c ${dconf} right &
fi
